<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.jpinpoint.sonar</groupId>
    <artifactId>sonar-pmd-jpinpoint-parent</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <name>Sonar PMD jPinpoint Parent</name>
    <description>Parent POM aggregating java-pmd7 and kotlin-pmd7 modules</description>
    <url>https://github.com/jborgers/sonar-pmd-jpinpoint</url>

    <modules>
        <module>java-pmd7</module>
        <module>kotlin-pmd7</module>
    </modules>

    <scm>
        <connection>scm:git:git@github.com:jborgers/sonar-pmd-jpinpoint.git</connection>
        <developerConnection>scm:git:git@github.com:jborgers/sonar-pmd-jpinpoint.git</developerConnection>
        <url>https://github.com/jborgers/sonar-pmd-jpinpoint</url>
        <tag>${revision}</tag>
    </scm>

    <licenses>
        <license>
            <name>Apache-2.0</name>
            <url>https://github.com/jborgers/sonar-pmd-jpinpoint/blob/master/LICENSE</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>Jeroen Borgers</name>
            <email>jborgers@jpinpoint.com</email>
        </developer>
        <developer>
            <name>Peter Paul Bakker</name>
            <email>peter.paul.bakker@stokpop.nl</email>
        </developer>
        <developer>
            <name>Vincent Oostindie</name>
            <email>Vincent.Oostindie@rabobank.nl</email>
        </developer>
    </developers>

    <profiles>
        <profile>
            <id>release</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>0.9.0</version>
                        <extensions>true</extensions>
                        <configuration>
                            <autoPublish>false</autoPublish>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <version>3.3.1</version>
                        <executions>
                            <execution>
                                <id>attach-sources</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>jar-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <version> 3.12.0</version>
                        <executions>
                            <execution>
                                <id>attach-javadoc</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <stylesheet>java</stylesheet>
                            <doclint>none</doclint>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>3.2.8</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <gpgArguments>
                                <arg>--pinentry-mode</arg>
                                <arg>loopback</arg>
                            </gpgArguments>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>