<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.jpinpoint.sonar</groupId>
        <artifactId>sonar-pmd-jpinpoint-parent</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>sonar-pmd-jpinpoint-java</artifactId>
    <packaging>sonar-plugin</packaging>

    <name>Sonar PMD jPinpoint rules for Java plugin</name>
    <description>${plugin.description}</description>

    <properties>
        <plugin.key>pmdjpinpoint</plugin.key>
        <plugin.name>jPinpoint rules for Java</plugin.name>
        <plugin.description>134 Rules for responsible Java programming built on PMD7, 83 on performance, 64 on sustainability, 34 on multi-threading, 11 on data mix-up.</plugin.description>
        <pmd.inputFileName>jpinpoint-rules-java.xml</pmd.inputFileName>
        <sonar.outputFileName>sonar-pmd-jpinpoint.xml</sonar.outputFileName>
    </properties>


    <dependencies>
        <dependency>
            <groupId>org.sonarsource.pmd</groupId>
            <artifactId>sonar-pmd-lib</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.sonarsource.api.plugin</groupId>
            <artifactId>sonar-plugin-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.sourceforge.pmd</groupId>
            <artifactId>pmd-core</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.sourceforge.pmd</groupId>
            <artifactId>pmd-java</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.junit</groupId>
            <artifactId>junit-bom</artifactId>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>

            <plugin>
                <groupId>org.sonarsource.sonar-packaging-maven-plugin</groupId>
                <artifactId>sonar-packaging-maven-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <pluginClass>com.jpinpoint.sonar.PmdJavaExtensionPlugin</pluginClass>
                    <basePlugin>pmd</basePlugin>
                    <pluginName>PMD jPinpoint rules for Java</pluginName>
                    <pluginKey>${plugin.key}</pluginKey>
                    <pluginDescription>${plugin.description}</pluginDescription>
                    <pluginUrl>https://github.com/jborgers/sonar-pmd-jpinpoint</pluginUrl>
                    <pluginIssueTrackerUrl>https://github.com/jborgers/sonar-pmd-jpinpoint/issues</pluginIssueTrackerUrl>
                    <pluginOrganizationName>jPinpoint, Stokpop and Rabobank</pluginOrganizationName>
                    <pluginOrganizationUrl>https://github.com/jborgers/PMD-jPinpoint-rules/tree/v2.1.1#pmd-jpinpoint-rules</pluginOrganizationUrl>
                    <requiredForLanguages>java</requiredForLanguages>
                    <archive>
                        <manifestEntries>
                            <!-- ${buildNumber} is the svn revision generated by the buildnumber-maven-plugin -->
                            <!--suppress UnresolvedMavenProperty -->
                            <Implementation-Build>${buildNumber}</Implementation-Build>
                            <!--suppress UnresolvedMavenProperty -->
                            <Build-Time>${timestamp}</Build-Time>
                            <Plugin-RequiredForLanguages>java</Plugin-RequiredForLanguages>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>


            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                        <configuration>
                            <formats>
                                <format>XML</format>
                            </formats>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>xml-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>transform</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
