<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.jpinpoint.sonar</groupId>
        <artifactId>sonar-pmd-jpinpoint-parent</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>sonar-pmd-jpinpoint-kotlin</artifactId>
    <packaging>sonar-plugin</packaging>

    <name>Sonar PMD jPinpoint rules for Kotlin plugin</name>

    <properties>
        <plugin.key>pmdjpinpointkotlin</plugin.key>
        <plugin.name>jPinpoint rules for Kotlin</plugin.name>
        <plugin.description>13 Rules for responsible Kotlin programming built on PMD7.</plugin.description>
        <pmd.inputFileName>jpinpoint-rules-kotlin.xml</pmd.inputFileName>
        <sonar.outputFileName>sonar-pmd-jpinpoint-kotlin.xml</sonar.outputFileName>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.sonarsource.pmd</groupId>
            <artifactId>sonar-pmd-lib</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.sonarsource.api.plugin</groupId>
            <artifactId>sonar-plugin-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.sourceforge.pmd</groupId>
            <artifactId>pmd-core</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.sourceforge.pmd</groupId>
            <artifactId>pmd-kotlin</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.sonarsource.sonar-packaging-maven-plugin</groupId>
                <artifactId>sonar-packaging-maven-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <pluginClass>com.jpinpoint.sonar.PmdKotlinExtensionPlugin</pluginClass>
                    <basePlugin>pmd</basePlugin>
                    <pluginName>${plugin.name}</pluginName>
                    <pluginKey>${plugin.key}</pluginKey>
                    <pluginDescription>${plugin.description}</pluginDescription>
                    <pluginUrl>https://github.com/jborgers/sonar-pmd-jpinpoint</pluginUrl>
                    <pluginIssueTrackerUrl>https://github.com/jborgers/sonar-pmd-jpinpoint/issues</pluginIssueTrackerUrl>
                    <requiredForLanguages>kotlin</requiredForLanguages>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>xml-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>transform</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
