name: Build, test and release SNAPSHOT

on:
  push:
    paths-ignore:
      - '.github/**'
      - '**/*.md'
    tags-ignore:
      - '**'
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      skipTests:
        description: "Skip Tests?"
        required: true
        default: false
        type: boolean
      enableDebug:
        description: "Debug?"
        required: true
        default: false
        type: boolean

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v5

      - name: Set Release version env variable
        working-directory: ./java-pmd7
        run: |
          echo "TAG_NAME=$(../mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      # only build SNAPSHOTS, use release for tagged releases
      - name: Check if tag contains SNAPSHOT
        if: contains(env.TAG_NAME, 'SNAPSHOT') != true
        run: |
          echo "Tag '$TAG_NAME' does not contain 'SNAPSHOT', failing build."
          exit 1

      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Build plugin jars
        env:
          SKIP_TESTS: ${{ github.event.inputs.skipTests }}
          ENABLE_DEBUG: ${{ github.event.inputs.enableDebug }}
        run: |
          ../mvnw $(if [ "$ENABLE_DEBUG" == "true" ]; then echo "-X"; fi) --batch-mode $(if [ "$SKIP_TESTS" == "true" ]; then echo "-DskipTests"; fi) package

      - name: Upload java plugin jar to github actions build
        uses: actions/upload-artifact@v4
        with:
          name: sonar-pmd-jpinpoint-java-${{ env.TAG_NAME }}.jar
          path: java-pmd7/target/sonar-pmd-jpinpoint-java-${{ env.TAG_NAME }}.jar

      - name: Upload kotlin plugin jar to github actions build
        uses: actions/upload-artifact@v4
        with:
          name: sonar-pmd-jpinpoint-kotlin-${{ env.TAG_NAME }}.jar
          path: kotlin-pmd7/target/sonar-pmd-jpinpoint-kotlin-${{ env.TAG_NAME }}.jar

      - name: Upload JARs to pre-release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Pre-release ${{ env.TAG_NAME }}
          prerelease: true
          files: |
            java-pmd7/target/sonar-pmd-jpinpoint-java-${{ env.TAG_NAME }}.jar
            kotlin-pmd7/target/sonar-pmd-jpinpoint-kotlin-${{ env.TAG_NAME }}.jar
          body: |
            Automated pre-release build for version ${{ env.TAG_NAME }}
            
            Built from commit: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish SNAPSHOT to Maven Central
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD}}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSWORD }}
          SKIP_TESTS: ${{ github.event.inputs.skipTests }}
          ENABLE_DEBUG: ${{ github.event.inputs.enableDebug }}
        run: ../mvnw $(if [ "$ENABLE_DEBUG" == "true" ]; then echo "-X"; fi) $(if [ "$SKIP_TESTS" == "true" ]; then echo "-DskipTests"; fi) -P release --batch-mode deploy
