name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Set version
        working-directory: ./java-pmd6
        run: |
          ../mvnw versions:set -DnewVersion=${{ github.event.release.tag_name }}
          ../mvnw versions:set-scm-tag -DnewTag=${{ github.event.release.tag_name }}

      - name: Publish package
        working-directory: ./java-pmd6
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD}}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSWORD }}
        run: ../mvnw -P release --batch-mode deploy -DskipTests
